# Generated by Django 2.1.1 on 2018-09-12 06:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_file_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('name', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='same_family',
            new_name='FamilyFatent',
        ),
        migrations.RemoveField(
            model_name='apply_patent',
            name='patent',
        ),
        migrations.RemoveField(
            model_name='family_nation',
            name='patent',
        ),
        migrations.AlterField(
            model_name='file_test',
            name='file',
            field=models.FileField(upload_to=main.models.test_dir_path),
        ),
        migrations.AlterField(
            model_name='patent',
            name='branch1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='patent',
            name='branch2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='patent',
            name='branch3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='patent',
            name='cat_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patent',
            name='invent_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patent',
            name='tech_prob',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='apply_patent',
        ),
        migrations.DeleteModel(
            name='family_nation',
        ),
        migrations.AddField(
            model_name='patent',
            name='applicants',
            field=models.ManyToManyField(to='main.Applicant'),
        ),
        migrations.AddField(
            model_name='patent',
            name='nations',
            field=models.ManyToManyField(to='main.Nation'),
        ),
    ]
